### ISSUE TITLE
Make the wiki editable

### ISSUE THREAD

**Issue by mandar1jn** [TheCherno/Hazel#375] opened 2020-11-27 10:51 UTC
Could you please give us the ability to edit the wiki? I wanted to add a how to build page, but I can't edit it and when forking it it doesn't fork the wiki

**Comment by mandar1jn** [comment] 2020-11-27 10:59
[download the source.txt](https://github.com/TheCherno/Hazel/files/5607471/download.the.source.txt)
just as an example. I couldn't upload a md file

**Comment by MMS-27** [comment] 2020-11-28 09:22
The Wiki is Being Edited at the Cherno Community Repository . Please Check that One There

**Comment by LovelySanta** [comment] 2020-11-28 13:10
I'll close this as duplicate of #353
See https://github.com/TheCherno/Hazel/issues/353#issuecomment-715925011 for more information, you can create a PR to the community repository with your contribution. It would be highly appreciated!

**Closed by LovelySanta** 2020-11-28 13:10 UTC
