### ISSUE TITLE
Build fails: Linker error Runtime-lib mismatch

### ISSUE THREAD

**Issue by LostInCompilation** [TheCherno/Hazel#459] opened 2021-07-19 01:02 UTC
I created the Solution files using the included python scripts for VisualStudio2019. When building with VS, Hazelnut and Sandbox are failing because of linker errors. I did not modify the runtime library to use, everything is at default, no change on my side.

Every project inside the solution uses MultithreadDebugDLL runtime libs. So what (I assume external) component is causing this?

Linker output (only a few selected, there are hundred of repetaed errors):
```
yaml-cpp.lib(stream.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in ExampleLayer.obj

msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: __cdecl std::_Locinfo::_Locinfo(char const *)" (??0_Locinfo@std@@QEAA@PEBD@Z) already defined in yaml-cpp.lib(stream.obj)

libcpmtd.lib(locale.obj) : error LNK2005: "public: char const * __cdecl std::_Locinfo::_Getfalse(void)const " (?_Getfalse@_Locinfo@std@@QEBAPEBDXZ) already defined in msvcprtd.lib(MSVCP140D.dll)
```

**Comment by WarEagle451** [comment] 2021-07-19 04:01
In the yaml premake file change static runtime to "off", this is the same issue as #457

**Comment by LovelySanta** [comment] 2021-07-19 15:06
Closing as duplicate of #457

**Closed** 2021-07-19 15:06 UTC
Labels: Impact:Duplicate

**Comment by LostInCompilation** [comment] 2021-07-20 01:48
Thanks.

Will this be fixed in an upcoming release?

**Comment by LovelySanta** [comment] 2021-07-20 15:24
> Thanks.
> 
> Will this be fixed in an upcoming release?

It depends when Cherno merges https://github.com/TheCherno/yaml-cpp/pull/1 as mentioned in #457.

> And sorry for duplicate, but "Errors on Running" is just a really bad title when it comes to searching for this error beforehand...

I've changed the title of #457.
