### ISSUE TITLE
This license is not valid due to missing information.

### ISSUE THREAD

**Issue by OldAccBye** [TheCherno/Hazel#431] opened 2021-03-27 13:34 UTC
https://github.com/TheCherno/Hazel/blob/a16f605b3aa82ecf1c47ebd5d505127de81028f2/LICENSE#L189

The problem here is that this license (once it is valid) is legally only valid for the next updates ... for the current source code, this license does not apply to anyone ...

**Comment by LovelySanta** [comment] 2021-03-28 08:06
Closing this as duplicate of #109 

The gist is that this notice is required in each file.

**Closed by LovelySanta** 2021-03-28 08:06 UTC
