### ISSUE TITLE
Memory leak in layerstack

### ISSUE THREAD

**Issue by LeOwnYa** [TheCherno/Hazel#61] opened 2019-05-19 09:39 UTC
Found a huge memory leak which is cause by ImGui as we do not shut everything down.
Inside LayerStack destructor we need to make sure that OnDetach is called.

```
LayerStack::~LayerStack()
{
	for (Layer* layer : m_Layers)
	{
		layer->OnDetach();		// Just added this
		delete layer;
	}
}
```

**Comment by CleverSource** [comment] 2019-05-19 14:53
I talked about this a bit here, I noticed it before but could never find the root cause. You should definitely add to my post if you'd like. 

https://github.com/TheCherno/Hazel/issues/47

**Comment by CleverSource** [comment] 2019-05-20 21:43
#47

**Comment by Gaztin** [comment] 2019-06-06 14:54
Duplicate of #47. Closing.

**Closed by Gaztin** 2019-06-06 14:54 UTC
