### ISSUE TITLE
Application crash on windows default full-screen toggling

### ISSUE THREAD

**Issue by L4ZZA** [TheCherno/Hazel#43] opened 2019-02-25 16:36 UTC
I assume windows is trying to force our application to fullscreen mode, but then something goes wrong. (See image below)

![image](https://user-images.githubusercontent.com/17835185/53352782-56857d80-391b-11e9-9188-5a51b720d179.png)

**Steps**:
- Run the application
- Press F12

**Bug**: 
Application crashes

**Expected**: 
Nothing should happen at least or full screen should be toggled.

**Comment by Dragon9815** [comment] 2019-02-25 19:47
This is an intended feature of Windows. Hitting F12 when a debugger is attached to a program immediately triggers a breakpoint. 

>The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident.

[Source (MSDN)](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-registerhotkey)

**Comment by TheCherno** [comment] 2019-02-28 22:24
Closing because this works as intended.

**Closed by TheCherno** 2019-02-28 22:24 UTC
