### ISSUE TITLE
EditorLayer.cpp ImGuizmo.h not found build error

### ISSUE THREAD

**Issue by hackerManik3** [TheCherno/Hazel#529] opened 2021-12-29 10:29 UTC
i got this error after building please help...
Build started...
1>------ Build started: Project: Hazel, Configuration: Debug x64 ------
1>ImGuiLayer.cpp
1>C:\Users\KULDEEP SHARMA\Desktop\Hazel\Hazel\src\Hazel\ImGui\ImGuiLayer.cpp(90,3): error C2653: 'ImGuizmo': is not a class or namespace name
1>C:\Users\KULDEEP SHARMA\Desktop\Hazel\Hazel\src\Hazel\ImGui\ImGuiLayer.cpp(90,13): error C3861: 'BeginFrame': identifier not found
1>Done building project "Hazel.vcxproj" -- FAILED.
2>------ Build started: Project: Hazelnut, Configuration: Debug x64 ------
2>EditorLayer.cpp
2>C:\Users\KULDEEP SHARMA\Desktop\Hazel\Hazelnut\src\EditorLayer.cpp(11,10): fatal error C1083: Cannot open include file: 'ImGuizmo.h': No such file or directory
2>Done building project "Hazelnut.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 4 up-to-date, 0 skipped ==========

**Comment by WarEagle451** [comment] 2021-12-30 05:37
Looks like ImGuizmo wasn't pulled correctly. Try re-downloading the repository, if that doesn't you'll have to manually place it into the vendor folder

**Comment by LovelySanta** [comment] 2022-01-02 11:11
Closing as not a bug.

**Closed by LovelySanta** 2022-01-02 11:11 UTC
Labels: Impact:Question
