### ISSUE TITLE
Bug closing the gui with WindowsWindow.h Events

### ISSUE THREAD

**Issue by Cankar001** [TheCherno/Hazel#86] opened 2019-07-23 08:54 UTC
If you implement the events in WindowsWindow.h like in the tutorial, I discovered that if you not click the standard close button but the minimize or maximize button the application gets shutdown as well. Same for resizing the window on the top side. Any idea why this happens?

**Comment by LostMikely** [comment] 2019-07-26 00:42
This does not happen for me. I think you have made a mistake somewhere.

**Comment by LovelySanta** [comment] 2019-07-26 09:04
Does this also happen on the actual Hazel repo? I can't reproduce this... For help with your own engine I would refer you to [TheCherno Discord server](https://discord.gg/K2eSyQA)

**Comment by WhoseTheNerd** [comment] 2019-07-26 18:45
> If you implement the events in WindowsWindow.h like in the tutorial

**All issues/bugs should be reproducible on this repo!** 
If you any questions about your code, then as @LovelySanta said, refer to [TheCherno Discord server](https://discordapp.com/invite/K2eSyQA)

**Comment by LovelySanta** [comment] 2019-07-26 19:08
Maybe we can add some information to the templates in #80 to state it clearly that issues/PR's must be part of this repo and not from your own code-along with the videos? Any suggestions on that @WhoseTheNerd ?

**Comment by CleverSource** [comment] 2019-08-25 16:41
I believe this issue should be closed. It was unrelated to the Hazel repository.

**Comment by LovelySanta** [comment] 2019-08-25 17:21
It is still a bug... Not all, but partialy.

1. Minimizing is still executing the rendering (not a huge issue, I can live with this). So I call the minimize button working as expected.
2. Maximizing / Any resizing isn't working. It still has unintended behaviour, it might not be shutting down the engine, but it isn't working correctly for sure.
This is how it looks when I start Hazel: 
![image](https://user-images.githubusercontent.com/26593477/63653440-ea21f480-c76c-11e9-8fd0-b28ddded7527.png)
And this is how it looks after pressing the maximize button:
![image](https://user-images.githubusercontent.com/26593477/63653445-fad26a80-c76c-11e9-875c-05c2c161161a.png)
A more clear detail (after rotating the camera) shows that the windows is still the same size, but rendered in the bottom left corner:
![image](https://user-images.githubusercontent.com/26593477/63653454-1a699300-c76d-11e9-915e-ef154825de37.png)
This is an example of resizing to a bigger size, resizing to a smaller size has the same effect, it renders the bottom left corner of the actual rendered space.

**Comment by LovelySanta** [comment] 2019-10-05 20:05
This was fixed in https://github.com/TheCherno/Hazel/commit/2b37c04ae1c7264f23f6af2d6c384ecc909f3b60

**Closed by LovelySanta** 2019-10-05 20:05 UTC
Labels: Impact:Bug
